webapps/upis/tehnicka/urls.py
from django.urls import path

from django.urls import path
from . import views
# we could say: from application import views as application_view and use it as application_view.details

app_name = 'tehnicka'
urlpatterns = [
    path("", views.index_base, name='index_base'),
    path("smjer/<int:smjer_id>", views.index, name='index'),
    path("details/<int:ucenik_id>", views.details, name='details'),
    path("delete/<int:ucenik_id>", views.delete, name='delete'),
    path("add-student/", views.dodajucenika, name='dodajucenika'),
    path("details/priznanje/<int:priznanje_id>", views.brisipriznanje, name='brisipriznanje'),
]

webapps/upis/upis/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tscze/", include("tehnicka.urls")),
    path("login/", include("users.urls"))
]

webapps/upis/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
#    path("ucenici", views.ucenici_view, name="ucenici"),
]

webapps/upis/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from tehnicka.models import Ucenik, Smjer, Predmet

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {"message": None})
    context = {
        "user": request.user
    }
    #return HttpResponse(request.user.username)
    return render(request, "users/user.html", context)

def login_view(request):
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "users/login.html", {"message": "Invalid credentials."})

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {"message": "Logged out."})

webapps/upis/users/templates/users/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
          {% block title%}
          {% endblock %}
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
    <body>
      <div class="container">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
          <ul class="navbar-nav ml-auto">

            {% if request.user.is_authenticated %}
            <li class="nav-item"> <a class="nav-link" href="{% url 'tehnicka:index_base' %}"> Lista ucenika</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'tehnicka:dodajucenika' %}"> Dodaj ucenika</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'logout' %}"> Logout</a> </li>
            {% else %}
            <li class="nav-item"> <a class="nav-link" href="{% url 'index' %}"> Login</a> </li>
            {% endif %}
          </ul>
        </nav>

      </div>
        {% block body %}
        {% endblock %}
    </body>
</html>

webapps/upis/users/templates/users/login.html
{% extends "users/base.html" %}
{% block title%}
  Login
{% endblock %}
{% block body %}

<div class="container">
  <h1 style="text-align:center">Login</h1>
  {% if message %}
      <p style="text-align:center" class="help-block">
          {{ message }}
      </p>
  {% endif %}
  <div class="container">
    <div class="row">
      <div style="width:30%; margin:0 auto;">
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="username"> Username: </label>
              <input id="username" class="form-control" name="username" type="text" placeholder="User name"/>
            </div>
            <div class="form-group">
              <label for="pass">Password: </label>
              <input id="pass" class="form-control" name="password" type="password" placeholder="Password"/>
            </div>
            <button class="btn btn-secondary" type="submit" name="button"> Login </button>
            <!-- <input class="btn btn-default" type="submit" value="Login"/> -->
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

webapps/upis/users/templates/users/user.html
{% extends "users/base.html" %}
{% block title %}
  Zdravo {{ user.username}}
{% endblock %}


{% block body %}
<div class="container">

  <div class="jumbotron">
    <h1> Upis učenika u prvi razred 2019/2020</h1>
    <h3> Tehnička škola Zenica </h3>
  </div>
  <div class="continaer">
      <h1>Zdravo {{ user.username }}</h1>

    <p class="help-block">
      Pristupite unosu novog ucenika.
    </p>
  </div>
  <hr>

</div>
{% endblock %}