webapps/upis/tehnicka/urls.py
from django.urls import path

from django.urls import path
from . import views
# we could say: from application import views as application_view and use it as application_view.details

app_name = 'tehnicka'
urlpatterns = [
    path("", views.index_base, name='index_base'),
    path("smjer/<int:smjer_id>", views.index, name='index'),
    path("details/<int:ucenik_id>", views.details, name='details'),
    path("delete/<int:ucenik_id>", views.delete, name='delete'),
    path("add-student/", views.dodajucenika, name='dodajucenika'),
    path("details/priznanje/<int:priznanje_id>", views.brisipriznanje, name='brisipriznanje'),
]

webapps/upis/upis/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tscze/", include("tehnicka.urls")),
    path("login/", include("users.urls"))
]

webapps/upis/tehnicka/models.py
from django.db import models
import datetime


# Create your models here.
class Smjer(models.Model):
    # blank odnosi se na formu (false nije dozvoljeno ostaviti prazno polje)
    kod=models.CharField(max_length=3, default='AUT', blank=False)
    naziv=models.CharField(max_length=64)
    class Meta:
        verbose_name_plural = "smjerovi"
    def __str__(self):
        return f"id:{self.id}:{self.kod}-{self.naziv}"

def current_year():
    return datetime.date.today().year

def year_choices():
    return [(r,r) for r in range(1984, datetime.date.today().year+1)]

class Ucenik(models.Model):
    ime=models.CharField(max_length=50)
    prezime=models.CharField(max_length=50)
    # JMBG=models.IntegerField(null=True, blank=False)
    osnovna_skola=models.CharField(max_length=50)
    smjer=models.ForeignKey(Smjer, on_delete=models.CASCADE)
    godina_upisa = models.IntegerField(default=current_year)
    # Ukoliko ne bismo trazili listanje po smjerovima
    #smjer=model.CharField(max_length=3,choices=smjerovi, default=automaticar)
    # opcionalno bi trebalo napraviti izbor za 3 smjera (manytomany)

    #DEFAULT_DIPLOMA_ID=0 # will fail foreign key constraint
    #diploma_id=models.ForeignKey(Diploma,on_delete=models.CASCADE)
    #onetoonefield same as foreignkey and unique=True
    #diploma=models.OneToOneField(Diploma, on_delete=models.CASCADE)
    elektronicar = 'ELE'
    automaticar = 'AUT'
    arhitekt = 'ARH'
    masinac = 'MAS'
    metalurg='MET'
    smjerovi = (
    (elektronicar, 'Tehničar elektronike'),
    (automaticar, 'Tehničar računarske tehnike i automatike'),
    (arhitekt, 'Arhitektonski tehničar'),
    (masinac, 'Mašinski tehničar'),
    (metalurg, 'Metalurški tehničar'),
    )
    class Meta:
        verbose_name_plural = "Učenici"
    def __str__(self):
        return f"id:{self.id}:{self.ime}-{self.prezime}"

# class Takmicenje(models.Model):
#     kod=models.CharField(max_length=64)
#     naziv=models.CharField(max_length=64)
#     class Meta:
#         verbose_name_plural = "Takmicenja"
#     def __str__(self):
#         return f"{self.kod}-{self.naziv}"

class Priznanja(models.Model):
    naziv=models.CharField(max_length=64)
    bodovi=models.IntegerField(default='0')
    ucenik_id=models.ForeignKey(Ucenik, on_delete=models.CASCADE)
    # vrsta_takmicenja=models.ForeignKey(Takmicenje, on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = "Priznanja"
    def __str__(self):
        return f"id:{self.id}:{self.naziv}-{self.bodovi}"

class PredmetIspis(models.Model):
    kod=models.CharField(max_length=2, default='MM', blank=False)
    naziv=models.CharField(max_length=64)
    razred_id=models.IntegerField(default='5')
    class Meta:
        verbose_name_plural = "Predmeti_ispis"
    def __str__(self):
        return f"{self.razred_id}:{self.naziv}-{self.kod}"

class Predmet(models.Model):
    kod=models.CharField(max_length=2, default='MM', blank=False)
    naziv=models.CharField(max_length=64)
    ocjena=models.IntegerField(null=True, blank=True)
    # diploma_id=models.ForeignKey(Diploma,on_delete=models.CASCADE) not defined
    class Meta:
        verbose_name = 'Predmet'
        verbose_name_plural = 'Predmeti'
    def __str__(self):
        return f"id:{self.id} {self.kod}-{self.naziv}"
'''
    def save(self, *args, **kwargs):
     if not self.ocjena:
          self.ocjena = None
     super(Predmet, self).save(*args, **kwargs)
'''
class Diploma(models.Model):
    razred_id=models.IntegerField(null=False, blank=False)
    razred_naziv=models.CharField(max_length=64)
    predmeti=models.ManyToManyField(Predmet)
    ucenik_id=models.ForeignKey(Ucenik, on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = "Diplome"
    def __str__(self):
        return f"id:{self.id} {self.razred_naziv}"

webapps/upis/tehnicka/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect

from tehnicka.models import Ucenik, Smjer, Predmet, Diploma, PredmetIspis, Priznanja
from django.contrib.auth import authenticate, login, logout

from django.urls import reverse

from django.db import transaction
import json
#### ---------------- INDEX VIEW  ---------------- ####
# INDEX: This view should show all students with corresponding classes and grades
def index_base(request):
    context={
    'smjerovi': Smjer.objects.all()
    }
    return render(request, 'tehnicka/index_base.html',context)

def index(request, smjer_id):
    message=''
    if request.session.get('message'):
        message='Korisnik obrisan!'
        del request.session['message']

    posebni_bodovi={}
    prosjek_6={}
    prosjek_7={}
    prosjek_8={}
    prosjek_9={}

    prosjek_ukupno=0
    posebni_predmet_ukupno=0
    posebni_predmet_1_ocjena_razred9=0
    posebni_predmet_2_ocjena_razred9=0
    posebni_predmet_3_ocjena_razred7=0
    UKUPNO=0
    posebni_predmet_1_ocjena_razred8=posebni_predmet_1_ocjena_razred9
    posebni_predmet_2_ocjena_razred8=posebni_predmet_2_ocjena_razred9
    posebni_predmet_3_ocjena_razred6=posebni_predmet_3_ocjena_razred7

    posebni_predmet_1=""
    posebni_predmet_2=posebni_predmet_1
    posebni_predmet_3=posebni_predmet_1

    # Dictionaries
    posebni_predmet_1_ocjena_razred8_dict={}
    posebni_predmet_1_ocjena_razred9_dict={}
    posebni_predmet_2_ocjena_razred8_dict={}
    posebni_predmet_2_ocjena_razred9_dict={}
    posebni_predmet_3_ocjena_razred6_dict={}
    posebni_predmet_3_ocjena_razred7_dict={}
    prosjek_ukupno_dict={}

    prosjek_6_dict={}
    prosjek_7_dict={}
    prosjek_8_dict={}
    prosjek_9_dict={}
    posebni_bodovi_dict={}
    ukupno_dict={}

    # Pokupi bodove sa priznanja
    priznanje_opcinsko_dict={} # @todo
    priznanje_kantonalno_dict={}
    priznanje_federalno_dict={}

# =============== Racunanje statistike ===============
    for ucenik in Ucenik.objects.filter(smjer=smjer_id):
        s=0 # prosjek po razredu laznjak -> brisi

        for razred in Diploma.objects.filter(ucenik_id=ucenik):
            p=0 # broj predmeta
            s1=0 # prosjek po razredu
            for predmet in razred.predmeti.all():
                p=p+1
                s1=s1+predmet.ocjena
                # Handling posebni_bodovi na predmete automatika/arhitekture/energetike
                if(ucenik.smjer.kod == 'AUT' or ucenik.smjer.kod == 'ARH' or ucenik.smjer.kod == 'EL'):
                    posebni_predmet_1="Matematika"
                    posebni_predmet_2="Fizika"
                    posebni_predmet_3="Informatika"
                    # RACUNAJ UKUPNE BODOVE NA POSEBNE PREDMETE
                    if razred.razred_id==8 or razred.razred_id==9:
                        if predmet.kod=='MM' or predmet.kod=='FI':
                            s=s+predmet.ocjena

                    if razred.razred_id==6 or razred.razred_id==7:
                        if predmet.kod=='IN':
                            s=s+predmet.ocjena

                    # RACUNAJ POJEDINACNE BODOVE NA POSEBNE PREDMETE
                    if predmet.kod=='MM' and razred.razred_id==8:
                        posebni_predmet_1_ocjena_razred8=predmet.ocjena
                    elif predmet.kod=='MM' and razred.razred_id==9:
                        posebni_predmet_1_ocjena_razred9=predmet.ocjena
                    elif predmet.kod=='FI' and razred.razred_id==8:
                        posebni_predmet_2_ocjena_razred8=predmet.ocjena
                    elif predmet.kod=='FI' and razred.razred_id==9:
                        posebni_predmet_2_ocjena_razred9=predmet.ocjena
                    elif predmet.kod=='IN' and razred.razred_id==6:
                        posebni_predmet_3_ocjena_razred6=predmet.ocjena
                    elif predmet.kod=='IN' and razred.razred_id==7:
                        posebni_predmet_3_ocjena_razred7=predmet.ocjena

                # Handling posebni_bodovi na predmete masinci/metalurzi
                if(ucenik.smjer.kod == 'MAS' or ucenik.smjer.kod == 'ME'):
                    posebni_predmet_1="Matematika"
                    posebni_predmet_2="Fizika"
                    posebni_predmet_3="Tehnička kultura"
                    # RACUNAJ UKUPNE BODOVE NA POSEBNE PREDMETE
                    if razred.razred_id==8 or razred.razred_id==9:
                        if predmet.kod=='MM' or predmet.kod=='FI':
                            s=s+predmet.ocjena
                    if razred.razred_id==6 or razred.razred_id==7:
                        if predmet.kod=='TK':
                            s=s+predmet.ocjena

                    # RACUNAJ POJEDINACNE BODOVE NA POSEBNE PREDMETE
                    if predmet.kod=='MM' and razred.razred_id==8:
                        posebni_predmet_1_ocjena_razred8=predmet.ocjena
                    elif predmet.kod=='MM' and razred.razred_id==9:
                        posebni_predmet_1_ocjena_razred9=predmet.ocjena
                    elif predmet.kod=='FI' and razred.razred_id==8:
                        posebni_predmet_2_ocjena_razred8=predmet.ocjena
                    elif predmet.kod=='FI' and razred.razred_id==9:
                        posebni_predmet_2_ocjena_razred9=predmet.ocjena
                    elif predmet.kod=='TK' and razred.razred_id==6:
                        posebni_predmet_3_ocjena_razred6=predmet.ocjena
                    elif predmet.kod=='TK' and razred.razred_id==7:
                        posebni_predmet_3_ocjena_razred7=predmet.ocjena


                # Handling posebni_bodovi na predmete tehnicar drumskog saobracaja
                if(ucenik.smjer.kod == 'TDS'):
                    posebni_predmet_1="Matematika"
                    posebni_predmet_2="Fizika"
                    posebni_predmet_3="Geografija"
                    # RACUNAJ UKUPNE BODOVE NA POSEBNE PREDMETE
                    if razred.razred_id==8 or razred.razred_id==9:
                        if predmet.kod=='MM' or predmet.kod=='FI':
                            s=s+predmet.ocjena
                    if razred.razred_id==6 or razred.razred_id==7:
                        if predmet.kod=='GE':
                            s=s+predmet.ocjena

                    # RACUNAJ POJEDINACNE BODOVE NA POSEBNE PREDMETE
                    if predmet.kod=='MM' and razred.razred_id==8:
                        posebni_predmet_1_ocjena_razred8=predmet.ocjena
                    elif predmet.kod=='MM' and razred.razred_id==9:
                        posebni_predmet_1_ocjena_razred9=predmet.ocjena
                    elif predmet.kod=='FI' and razred.razred_id==8:
                        posebni_predmet_2_ocjena_razred8=predmet.ocjena
                    elif predmet.kod=='FI' and razred.razred_id==9:
                        posebni_predmet_2_ocjena_razred9=predmet.ocjena
                    elif predmet.kod=='GE' and razred.razred_id==6:
                        posebni_predmet_3_ocjena_razred6=predmet.ocjena
                    elif predmet.kod=='GE' and razred.razred_id==7:
                        posebni_predmet_3_ocjena_razred7=predmet.ocjena


            # Racunaj prosjek po razredima za svakog ucenika
            if(razred.razred_id==6):
                prosjek_6=round(s1/p,2) # round(x,2) float("{0:.2f}".format(x))

            if(razred.razred_id==7):
                prosjek_7=round(s1/p,2)
            if(razred.razred_id==8):
                prosjek_8=round(s1/p,2)
            if(razred.razred_id==9):
                prosjek_9=round(s1/p,2)

        # Pokupi zakljucne ocjene na 2 decimale i ukupnu prosjecnu ocjenu
        prosjek_6_dict[ucenik.id]=prosjek_6
        prosjek_7_dict[ucenik.id]=prosjek_7
        prosjek_8_dict[ucenik.id]=prosjek_8
        prosjek_9_dict[ucenik.id]=prosjek_9
        prosjek_ukupno_dict[ucenik.id]=round((prosjek_6+prosjek_7+prosjek_8+prosjek_9)*3,2)

        # Pokupi ocjene iz posebnih predmeta i ukupnu ocjenu
        posebni_predmet_1_ocjena_razred8_dict[ucenik.id]=posebni_predmet_1_ocjena_razred8
        posebni_predmet_1_ocjena_razred9_dict[ucenik.id]=posebni_predmet_1_ocjena_razred9
        posebni_predmet_2_ocjena_razred8_dict[ucenik.id]=posebni_predmet_2_ocjena_razred8
        posebni_predmet_2_ocjena_razred9_dict[ucenik.id]=posebni_predmet_2_ocjena_razred9
        posebni_predmet_3_ocjena_razred6_dict[ucenik.id]=posebni_predmet_3_ocjena_razred6
        posebni_predmet_3_ocjena_razred7_dict[ucenik.id]=posebni_predmet_3_ocjena_razred7
        #posebni_bodovi_suma
        posebni_bodovi_dict[ucenik.id]= posebni_predmet_1_ocjena_razred8 + posebni_predmet_1_ocjena_razred9+\
        posebni_predmet_2_ocjena_razred8+posebni_predmet_2_ocjena_razred9+\
        posebni_predmet_3_ocjena_razred6+posebni_predmet_3_ocjena_razred7

        priznanja=Priznanja.objects.filter(ucenik_id=ucenik)
        if not priznanja:
            priznanje_opcinsko_dict[ucenik.id]=0
            priznanje_kantonalno_dict[ucenik.id]=0
            priznanje_federalno_dict[ucenik.id]=0
        else:
            s_o=0
            for p in priznanja:
                s_o=s_o+p.bodovi
            priznanje_opcinsko_dict[ucenik.id]=s_o # {{ key }} - {{ value.i }}<
            priznanje_kantonalno_dict[ucenik.id]=0
            priznanje_federalno_dict[ucenik.id]=0

        ukupno_dict[ucenik.id]=round(prosjek_ukupno_dict[ucenik.id]+\
        posebni_bodovi_dict[ucenik.id]+\
        priznanje_opcinsko_dict[ucenik.id]+priznanje_kantonalno_dict[ucenik.id]+\
        priznanje_federalno_dict[ucenik.id], 2)


    #return HttpResponse(json.dumps( bodovi ))

# =============== Prikazivanje statistike ===============

    context={
    'ucenici':Ucenik.objects.filter(smjer=smjer_id),     # 'smjerovi':Smjer.objects.all(),
    'posebni_predmet_1':posebni_predmet_1,
    'posebni_predmet_2':posebni_predmet_2,
    'posebni_predmet_3':posebni_predmet_3,

webapps/upis/tehnicka/templates/tehnicka/index.html
{% extends "tehnicka/base.html" %}

{% block title%}
  Home
{% endblock %}

{% block body %}
  {% if message %}
  <div class="container">
    <p class="help-block">
          {{ message }}
    </p>

    </div>
  {% endif %}
  <div class="container">
    <!-- <div class="table-responsive" style="float: right; width: 50%">
      <form action="{% url 'tehnicka:dodajucenika' %}" method='GET'>
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary btn-lg">Dodaj ucenika <i class="fa fa-user-plus"></i></button>
      </form>
    </div> -->
    <h4 style="text-align:center">  Spisak ucenika </h4>
    <hr>
      <div class="table-responsive">
        <table class="table table-sm table-hover table-bordered">
          <thead>
            <tr>
              <th  class="table-info" scope="col" rowspan="2">#</th>
              <th  class="table-info" scope="col" rowspan="3">Ime</th>
              <th  class="table-info" scope="col" rowspan="3">Prezime</th>
              <th  class="table-info" scope="col" rowspan="3">Osnovna skola</th>
              <th  class="table-info" scope="col" rowspan="3" colspan="5" ><strong>I Opći kriterij </strong>
              <br> <em> Uspjeh VI-IX razreda o.š </em></th>
              <th  class="table-info" scope="col" rowspan="3" colspan="7" ><strong> II Posebni kriterij</strong>
              <br> <em> Relevantni nastavni predmeti </em></th>
              <th  class="table-info" scope="col" rowspan="3" colspan="3" ><strong>III Opći kriterij</strong>
              <br> <em> Uspjeh VI-IX razreda o.š</em></th>
              <th  class="table-danger" scope="col" rowspan="3"colspan="1">Suma</th>
              {% if request.user.is_authenticated %}
                <th class="table-info" scope="col" rowspan="3"colspan="2"></th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            <tr>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>

              <th  class="table-info" scope="col" rowspan="1" colspan="2" >{{ posebni_predmet_1}}</th>
              <th  class="table-info" scope="col" rowspan="1" colspan="2">{{ posebni_predmet_2}}</th>
              <th  class="table-info" scope="col" rowspan="1" colspan="2">{{ posebni_predmet_3}}</th>

              <th  class="table-danger" scope="col" rowspan="2" colspan="1"> <center> Ukupno </center>  </th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-danger" scope="col" rowspan="1"></th>
              {% if request.user.is_authenticated %}
                <th class="table-info" scope="col" rowspan="3"colspan="2"></th>
              {% endif %}
            </tr>

            <tr>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"> VI </th>
              <th class="table-info" scope="col" rowspan="1"> VII </th>
              <th class="table-info" scope="col" rowspan="1"> VIII </th>
              <th class="table-info" scope="col" rowspan="1"> IX </th>
              <th class="table-danger" scope="col" rowspan="1"> <center> Ukupno </center> </th>

              <th class="table-info" scope="col" rowspan="1"> VIII </th>
              <th class="table-info" scope="col" rowspan="1"> IX </th>
              <th class="table-info" scope="col" rowspan="1"> VIII </th>
              <th class="table-info" scope="col" rowspan="1"> IX </th>
              <th class="table-info" scope="col" rowspan="1"> VI </th>
              <th class="table-info" scope="col" rowspan="1"> VII </th>

              <th class="table-info" scope="col" rowspan="1">O</th>
              <th class="table-info" scope="col" rowspan="1">K</th>
              <th class="table-info" scope="col" rowspan="1">F</th>
              <th class="table-danger" scope="col" rowspan="1"></th>
            </tr>
            <!-- DATA -->
            <tr>
              {% for ucenik in ucenici %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ ucenik.ime }}</td>
                <td>{{ ucenik.prezime }}</td>
                <td>{{ ucenik.osnovna_skola }}</td>

                <!-- // I prosjek ocjena 6-9 -->
                {% for key, value in prosjek_6.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in prosjek_7.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in prosjek_8.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in prosjek_9.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                <!-- // I prosjek ocjena ukupno -->
                {% for key, value in prosjek_ukupno.items %}
                  {% if key == ucenik.id %}
                  <td class="table-danger">{{ value }}</td>
                  {% endif %}
                {% endfor%}

                <!-- // II posebni predmeti po smjerovima-->
                {% for key, value in posebni_predmet_1_ocjena_razred8.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_1_ocjena_razred9.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_2_ocjena_razred8.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_2_ocjena_razred9.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_3_ocjena_razred6.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_3_ocjena_razred7.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                <!-- // II posebni predmeti po smjerovima ukupno-->
                {% for key, value in posebni_predmet_ukupno.items %}
                  {% if key == ucenik.id %}
                  <td class="table-danger">{{ value }}</td>
                  {% endif %}
                {% endfor%}

                <!-- // III -->
                {% for key, value in priznanje_opcinsko.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in priznanje_kantonalno.items  %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in  priznanje_federalno.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                <!-- // SUMA I,II,III -->
                {% for key, value in  ukupno.items %}
                  {% if key == ucenik.id %}
                  <td class="table-danger" >{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% if request.user.is_authenticated %}
                  <td> <a href="{% url 'tehnicka:details' ucenik.id %}"> <span> Uredi </span><i class="fa fa-user"></i> </a> </td>
                  <td> <a href="{% url 'tehnicka:delete' ucenik.id %}"> <span> Izbriši </span><i class="fa fa-user-times"></i> </a> </td>
                {% endif %}

              </tr>
              {% endfor%}
                <!-- {% if stari_commit%}
                {% for ucenik in ucenici %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ ucenik.ime }}</td>
                  <td>{{ ucenik.prezime }}</td>
                  <td>{{ ucenik.JMBG }}</td>
                  <td>{{ ucenik.smjer.naziv }}</td>
                  <td>{{ bodovi}}</td>
                  <td> <a href="{% url 'tehnicka:details' ucenik.id %}"> <span> Uredi </span><i class="fa fa-user"></i> </a> </td>
                  <td> <a href="{% url 'tehnicka:delete' ucenik.id %}"> <span> Izbriši </span><i class="fa fa-user-times"></i> </a> </td>
                </tr>
                {% endfor%}
                {%endif%} -->
          </tbody>
        </table>
      </div>

    </div>

    <br>
    <br>
    <hr>



{% endblock %}

webapps/upis/tehnicka/templates/tehnicka/index_base.html
{% extends "tehnicka/base.html" %}
{%block title%}
  Spisak ucenika -svi
{% endblock %}
  <div class="container">
    <h4 style="text-align:center">  Spisak ucenika </h4>
    <div class="jumbotron">
      <h1> Upis učenika u prvi razred 2019/2020</h1>
      <h3> Tehnička škola Zenica </h3>
      <h3> 2019/2020 </h3>
    </div>
  </div>
{% block body %}
  <div class="container">
    {% for smjer in smjerovi%}
    {% if smjer.id == 1 %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv}} </span><i class="fa fa-bolt"></i> </a>
    {% endif %}
    {% if smjer.id == 2 %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv}} </span><i class="fa fa-microchip"></i> </a>
    {% endif %}
    {% if smjer.id == 3 %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv}} </span><i class="fa fa-building"></i> </a>
    {% endif %}
    {% if smjer.id == 4 %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv}} </span><i class="fa fa-industry"></i> </a>
    {% endif %}
    {% if smjer.id == 5 %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv}} </span><i class="fa fa-flask"></i> </a>
    {% endif %}
    <br>
    {% endfor %}
  </div>
{% endblock %}